/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Service_Controller;
import Model.Quanlysach_Model;

/**
 *
 * @author Tran Huu Phuc
 */
  public class Editmenu_Quanlysach extends javax.swing.JFrame {
  private Quanlysach_Model  quanlysach_Model;
  private Service_Controller service_Controller;
   
    public Editmenu_Quanlysach() {
        initComponents();
        this.setVisible(true);
        service_Controller = new Service_Controller();
        quanlysach_Model  = new Quanlysach_Model();
        
            
        //set hien thi khi  nd can sua len bang edit.. de xem trc khi sua lai
        field_maSach_edit.setText(quanlysach_Model.getMaSach());
        field_tenSach_edit.setText(quanlysach_Model.getTenSach());
        String loaiSach_Edit = quanlysach_Model.getLoaiSach();
        if(loaiSach_Edit != null){
            String [] lS_edit = loaiSach_Edit.split(",");
            for(String l: lS_edit){
                if(l.equals("vanHoc")){
                    jRadioButton_vanHoc_edit.setSelected(true);
                }
                if(l.equals("Khxh")){
                    jRadioButton_KHXH_edit.setSelected(true);
                }
                if(l.equals("Congnghe")){
                    jRadioButton_Congnghe_edit.setSelected(true);
                }
                if(l.equals("Dialy")){
                    jRadioButton_diaLy_edit.setSelected(true);
                }
            }
        }


        field_Nxb_edit.setText(quanlysach_Model.getNhaXuatBan());
        field_tacGia_edit.setText(quanlysach_Model.getTacGia());
        field_soLuong_edit.setText(String.valueOf(quanlysach_Model.getSoLuong()));
        
        
    }

    Editmenu_Quanlysach(String maSach_Quanlysach) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        label_maSach_edit = new javax.swing.JLabel();
        label_tenSach_edit = new javax.swing.JLabel();
        label_loaiSach_edit = new javax.swing.JLabel();
        label_Nxb_edit = new javax.swing.JLabel();
        label_tacGia_edit = new javax.swing.JLabel();
        label_soLuong_edit = new javax.swing.JLabel();
        field_maSach_edit = new javax.swing.JTextField();
        field_tenSach_edit = new javax.swing.JTextField();
        jRadioButton_vanHoc_edit = new javax.swing.JRadioButton();
        jRadioButton_KHXH_edit = new javax.swing.JRadioButton();
        jRadioButton_Congnghe_edit = new javax.swing.JRadioButton();
        field_Nxb_edit = new javax.swing.JTextField();
        field_tacGia_edit = new javax.swing.JTextField();
        jRadioButton_diaLy_edit = new javax.swing.JRadioButton();
        field_soLuong_edit = new javax.swing.JTextField();
        button_edit_capnhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_maSach_edit.setText("Mã sách");

        label_tenSach_edit.setText("Tên Sách");

        label_loaiSach_edit.setText("Loại sách");

        label_Nxb_edit.setText("Nhà xuất bản");

        label_tacGia_edit.setText("Tác giả");

        label_soLuong_edit.setText("Số lượng");

        field_maSach_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_maSach_editActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_vanHoc_edit);
        jRadioButton_vanHoc_edit.setText("Văn học");

        buttonGroup1.add(jRadioButton_KHXH_edit);
        jRadioButton_KHXH_edit.setText("KHXH");
        jRadioButton_KHXH_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_KHXH_editActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Congnghe_edit);
        jRadioButton_Congnghe_edit.setText("Công nghệ");

        buttonGroup1.add(jRadioButton_diaLy_edit);
        jRadioButton_diaLy_edit.setText("Địa lý");
        jRadioButton_diaLy_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_diaLy_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_tacGia_edit)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_soLuong_edit)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_tacGia_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(field_soLuong_edit)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_loaiSach_edit)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton_vanHoc_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_KHXH_edit)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_Congnghe_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_diaLy_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Nxb_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field_Nxb_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_tenSach_edit)
                            .addComponent(label_maSach_edit))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_tenSach_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(field_maSach_edit))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_maSach_edit)
                    .addComponent(field_maSach_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tenSach_edit)
                    .addComponent(field_tenSach_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_loaiSach_edit)
                    .addComponent(jRadioButton_vanHoc_edit)
                    .addComponent(jRadioButton_KHXH_edit)
                    .addComponent(jRadioButton_Congnghe_edit)
                    .addComponent(jRadioButton_diaLy_edit))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Nxb_edit)
                    .addComponent(field_Nxb_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tacGia_edit)
                    .addComponent(field_tacGia_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_soLuong_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_soLuong_edit))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        button_edit_capnhat.setText("Sữa đổi áp dụng");
        button_edit_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_capnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(button_edit_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(button_edit_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_maSach_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_maSach_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_maSach_editActionPerformed

    private void jRadioButton_KHXH_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_KHXH_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_KHXH_editActionPerformed

    private void jRadioButton_diaLy_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_diaLy_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_diaLy_editActionPerformed

    
    // thuc hien sưa update code xử lý sự kiện
    private void button_edit_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_capnhatActionPerformed
         // thiết lập nơi nhập đưa dl từ bàn phím vào các fiel tg ứng trên giao diện
                quanlysach_Model.setMaSach(field_maSach_edit.getText());
                quanlysach_Model.setTenSach(field_tenSach_edit.getText());
                // thiet lap cac radio button trong loai sach
                String lS = "";
                if(jRadioButton_vanHoc_edit.isSelected()){
                    lS +="vanHoc";
                }else if(jRadioButton_KHXH_edit.isSelected()){
                    lS += "Khxh";
                }else if(jRadioButton_Congnghe_edit.isSelected()){
                    lS += "Congnghe";
                }else if(jRadioButton_diaLy_edit.isSelected()){
                    lS += "Dialy";
                }
                quanlysach_Model.setLoaiSach(lS);

                quanlysach_Model.setNhaXuatBan(field_Nxb_edit.getText());
                quanlysach_Model.setTacGia(field_tacGia_edit.getText());
                quanlysach_Model.setSoLuong(Integer.parseInt(field_soLuong_edit.getText()));

                service_Controller.Update_Quanlysach(quanlysach_Model);

                // caapj nhat xong an di
                new Giaodien_main().setVisible(true);
                dispose();
    }//GEN-LAST:event_button_edit_capnhatActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_edit_capnhat;
    private javax.swing.JTextField field_Nxb_edit;
    private javax.swing.JTextField field_maSach_edit;
    private javax.swing.JTextField field_soLuong_edit;
    private javax.swing.JTextField field_tacGia_edit;
    private javax.swing.JTextField field_tenSach_edit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_Congnghe_edit;
    private javax.swing.JRadioButton jRadioButton_KHXH_edit;
    private javax.swing.JRadioButton jRadioButton_diaLy_edit;
    private javax.swing.JRadioButton jRadioButton_vanHoc_edit;
    private javax.swing.JLabel label_Nxb_edit;
    private javax.swing.JLabel label_loaiSach_edit;
    private javax.swing.JLabel label_maSach_edit;
    private javax.swing.JLabel label_soLuong_edit;
    private javax.swing.JLabel label_tacGia_edit;
    private javax.swing.JLabel label_tenSach_edit;
    // End of variables declaration//GEN-END:variables
}
